language: nix

os:
  - linux
  - osx

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - nix-env -iA $EMACS_VER -f https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz

env:
  - EMACS_VER=emacs-24-4
  - EMACS_VER=emacs-24-5
  - EMACS_VER=emacs-25-1
  - EMACS_VER=emacs-25-2
  - EMACS_VER=emacs-25-3
  - EMACS_VER=emacs-26-1
  - EMACS_VER=emacs-26-2
  - EMACS_VER=emacs-26-3
  - EMACS_VER=emacs-snapshot

script:
  ./test-startup.sh

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
