language: nix

install:
  # Enable downloadable pre-built binaries stored on cachix
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use emacs-ci
  - nix-env -iA $EMACS_VER -f https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz

env:
  - EMACS_VER=emacs-24-4
  - EMACS_VER=emacs-24-5
  - EMACS_VER=emacs-25-1
  - EMACS_VER=emacs-25-2
  - EMACS_VER=emacs-25-3
  - EMACS_VER=emacs-26-1
  - EMACS_VER=emacs-26-2
  - EMACS_VER=emacs-26-3

script:
  lsb_release -a && ./test-startup.sh

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
